# Generated by Django 5.1.7 on 2025-05-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_remove_drawing_title'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='places.place'),
            preserve_default=False,
        ),
    ]
