# Generated by Django 5.1.7 on 2025-04-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/qr_codes/')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='places.place')),
            ],
        ),
    ]
